name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "[Setup] Checkout Repository"
        uses: actions/checkout@v1

      - name: "[Setup] Ensure 'master' branch exists"
        run: |
          git fetch --tags
          git branch --create-reflog master origin/master

      - name: "[Setup] Create GitVersion"
        uses: docker://gittools/gitversion:5.1.3-linux-netcoreapp2.1
        with:
          args: /github/workspace /nofetch /exec /bin/sh /execargs "-c \"echo $GitVersion_FullSemVer > /github/workspace/version.txt\""

      - name: "[Debug] Dump Environment"
        run: env

      - name: "[Setup] Install .NET Core"
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.101

      - name: "[Coverage] Instrument with Sonar"
        env:
          SONARCLOUD_LOGIN: ${{ secrets.SONARCLOUD_LOGIN }}
        run: |
          VERSION=$(cat version.txt)
          dotnet tool install --global dotnet-sonarscanner --version 4.8.0
          ~/.dotnet/tools/dotnet-sonarscanner begin \
            /k:"KK578_Bashi.Core" \
            /o:"kk578" \
            /d:sonar.login="$SONARCLOUD_LOGIN" \
            /d:sonar.host.url=https://sonarcloud.io \
            /d:sonar.cs.opencover.reportsPaths="coverage/coverage.opencover.xml" \
            /d:sonar.cs.nunit.reportsPaths="test/*/TestResults/TestResults.xml" \
            /v:"$VERSION"

      - name: "[Build] NuGet Restore"
        run: dotnet restore

      - name: "[Build] Build Solution"
        run: |
          VERSION=$(cat version.txt)
          echo $VERSION
          dotnet build --configuration Release /p:Version=$VERSION /p:AssemblyVersion=$VERSION

      - name: "[Test] Run Tests"
        run: |
          dotnet test \
            --configuration Release \
            --no-build \
            test/Bashi.Core.Tests/Bashi.Core.Tests.csproj

      - name: "[Pack] Create NuGet Package"
        run: |
          VERSION=$(cat version.txt)
          echo $VERSION
          dotnet pack \
            --configuration Release \
            --no-build \
            /p:Version=$VERSION \
            /p:AssemblyVersion=$VERSION \
            /p:RepositoryBranch=${GITHUB_REF#refs/heads/} \
            /p:RepositoryCommit=$GITHUB_SHA
          dotnet nuget push src/Bashi.Core/bin/Release/Bashi.Core.*.nupkg" --source "github"

      - name: "[Coverage] Upload to SonarCloud"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONARCLOUD_LOGIN: ${{ secrets.SONARCLOUD_LOGIN }}
        run: |
          ~/.dotnet/tools/dotnet-sonarscanner end /d:sonar.login="$SONARCLOUD_LOGIN"

      - name: "[Coverage] Upload to Coveralls"
        uses: coverallsapp/github-action@v1.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: "./coverage/coverage.info"
